Users/nmalkapuram/integrating postgresql
microsoft/VirtualClient pull request #46
Opened 2023-01-17 17:45 UTC by nmalkapuram

Integrating Postgresql

Contents : 
1. Dependencies and unit tests
2. Executors, unit tests and functional tests
3. Parser and unit tests

2023-02-02 10:26 UTC, nmalkapuram commented on src/VirtualClient/VirtualClient.Actions/PostgreSQL/PostgreSQLExecutor.cs
> +    public class PostgreSQLState
Yes. The state is used in unit and functional testing.

2023-02-02 10:43 UTC, nmalkapuram commented on src/VirtualClient/VirtualClient.Main/profiles/PERF-POSTGRESQL.json
> +        "BlobName": "postgresql.2.0.0.zip",
sudo apt-get -y install postgresql-14 installs required binaries. The above mentioned  DependencyPackageInstallation installs few .tcl files and scripts that I created which are required to run server and client tasks. These files take parameters that needs to be updated at run time, so haven't added them as part of scripts in our codebase.

2023-02-03 04:59 UTC, nmalkapuram commented on src/VirtualClient/VirtualClient.Main/profiles/PERF-POSTGRESQL.json
> +      "Type": "HammerDbInstallation",
Yes we need it on both sides. When postgresql is installed we have few config files installed along with it which are required for hammerdb client to work as expected on client side. 
And hammerdb is required on client side to start server side task (Creating database and setup configuration at server side)

2023-02-06 16:30 UTC, brdeyo requested changes
Hopefully the comments will show up. Apologies as I did not understand that I needed to take an extra step here to submit my comments.

2023-02-08 03:32 UTC, nmalkapuram commented
> Hopefully the comments will show up. Apologies as I did not understand that I needed to take an extra step here to submit my comments.

Got them. Thank you

2023-02-08 18:11 UTC, brdeyo commented on src/VirtualClient/VirtualClient.Main/profiles/PERF-SQL-POSTGRESQL.json
> +  "Parameters": {
Please take a look at one of the other profiles that exist in source at the moment. We are starting to add 'Metadata' to the profiles to make them more and more self-describing. As of now we are including 2 or 3 metadata properties that you can see in the other profiles. Please integrate similar ones into this profile when you have a sec. Thanks!

2023-02-08 19:58 UTC, brdeyo approved these changes

2023-02-08 20:19 UTC, merged